# Size-25 von Mises fit audit and paper-faithful interference

This notebook checks whether the von Mises fitting completed correctly for the full primary grid, excluding `0.5` sparsity:

- `two_module_rnn`, `shared`, `sp=1.0`, `init_scale in {0.001, 0.01, 0.1, 1, 2}` at size `25`
- `two_module_rnn`, `shared`, `no_comms`, `init_scale in {0.001, 0.01, 0.1, 1, 2}` at size `25`
- `two_module_rnn`, `task_routed`, `sp=1.0`, `init_scale in {0.001, 0.01, 0.1, 1, 2}` at size `25`
- `two_module_rnn`, `task_routed`, `no_comms`, `init_scale in {0.001, 0.01, 0.1, 1, 2}` at size `25`
- `single_module_rnn`, `init_scale in {0.001, 0.01, 0.1, 1, 2}` at size `50` as the baseline comparison

It also shows how to compute **paper-faithful interference** from the generated fit CSVs:

- `interference = 1 - A_weight_A2`

Important note:

- This interference metric is primarily interpretable for `near` and `far`.
- `same` is not expected to support the same mixture-model interpretation.

In [122]:
from pathlib import Path
import json
import numpy as np
import pandas as pd

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 200)

project_root = Path.cwd()
if project_root.name != "a1b2_modular":
    if (project_root / "a1b2_modular").exists():
        project_root = project_root / "a1b2_modular"
    else:
        for parent in [project_root, *project_root.parents]:
            if parent.name == "a1b2_modular":
                project_root = parent
                break

data_root = project_root / "data" / "simulations"
print(f"project_root = {project_root}")
print(f"data_root    = {data_root}")

project_root = /home/kat/workspace/Structure-Function-Analysis-of-Network-Topologies/a1b2_modular
data_root    = /home/kat/workspace/Structure-Function-Analysis-of-Network-Topologies/a1b2_modular/data/simulations

In [123]:
INIT_LEVELS = [0.001, 0.01, 0.1, 1.0, 2.0]

TARGET_RUNS = [
    {
        "arch_group": "two_module_shared_sp1",
        "routing": "shared",
        "sparsity_label": "1.0",
        "init_scale": 0.001,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_nb2_init0.001_nb2_shared_sp1.0_sep_cr_RNN_init0.001",
    },
    {
        "arch_group": "two_module_shared_sp1",
        "routing": "shared",
        "sparsity_label": "1.0",
        "init_scale": 0.01,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_nb2_init0.01_nb2_shared_sp1.0_sep_cr_RNN_init0.01",
    },
    {
        "arch_group": "two_module_shared_sp1",
        "routing": "shared",
        "sparsity_label": "1.0",
        "init_scale": 0.1,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_nb2_init0.1_nb2_shared_sp1.0_sep_cr_RNN_init0.1",
    },
    {
        "arch_group": "two_module_shared_sp1",
        "routing": "shared",
        "sparsity_label": "1.0",
        "init_scale": 1.0,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_nb2_nb2_shared_sp1.0_sep_cr_RNN",
    },
    {
        "arch_group": "two_module_shared_sp1",
        "routing": "shared",
        "sparsity_label": "1.0",
        "init_scale": 2.0,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_nb2_init2_nb2_shared_sp1.0_sep_cr_RNN_init2",
    },
    {
        "arch_group": "two_module_shared_sp05",
        "routing": "shared",
        "sparsity_label": "0.5",
        "init_scale": 0.001,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_sp05_nb2_init0.001_nb2_shared_sp0.5_sep_cr_RNN_init0.001",
    },
    {
        "arch_group": "two_module_shared_sp05",
        "routing": "shared",
        "sparsity_label": "0.5",
        "init_scale": 0.01,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_sp05_nb2_init0.01_nb2_shared_sp0.5_sep_cr_RNN_init0.01",
    },
    {
        "arch_group": "two_module_shared_sp05",
        "routing": "shared",
        "sparsity_label": "0.5",
        "init_scale": 0.1,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_sp05_nb2_init0.1_nb2_shared_sp0.5_sep_cr_RNN_init0.1",
    },
    {
        "arch_group": "two_module_shared_sp05",
        "routing": "shared",
        "sparsity_label": "0.5",
        "init_scale": 1.0,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_sp05_nb2_nb2_shared_sp0.5_sep_cr_RNN",
    },
    {
        "arch_group": "two_module_shared_sp05",
        "routing": "shared",
        "sparsity_label": "0.5",
        "init_scale": 2.0,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_sp05_nb2_init2_nb2_shared_sp0.5_sep_cr_RNN_init2",
    },
    {
        "arch_group": "two_module_shared_no_comms",
        "routing": "shared",
        "sparsity_label": "no_comms",
        "init_scale": 0.001,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_no_comms_nb2_init0.001_nb2_shared_sp0_sep_cr_RNN_init0.001",
    },
    {
        "arch_group": "two_module_shared_no_comms",
        "routing": "shared",
        "sparsity_label": "no_comms",
        "init_scale": 0.01,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_no_comms_nb2_init0.01_nb2_shared_sp0_sep_cr_RNN_init0.01",
    },
    {
        "arch_group": "two_module_shared_no_comms",
        "routing": "shared",
        "sparsity_label": "no_comms",
        "init_scale": 0.1,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_no_comms_nb2_init0.1_nb2_shared_sp0_sep_cr_RNN_init0.1",
    },
    {
        "arch_group": "two_module_shared_no_comms",
        "routing": "shared",
        "sparsity_label": "no_comms",
        "init_scale": 1.0,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_no_comms_nb2_nb2_shared_sp0_sep_cr_RNN",
    },
    {
        "arch_group": "two_module_shared_no_comms",
        "routing": "shared",
        "sparsity_label": "no_comms",
        "init_scale": 2.0,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_no_comms_nb2_init2_nb2_shared_sp0_sep_cr_RNN_init2",
    },
    {
        "arch_group": "two_module_task_routed_sp1",
        "routing": "task_routed",
        "sparsity_label": "1.0",
        "init_scale": 0.001,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_task_routed_nb2_init0.001_nb2_task_routed_sp1_sep_cr_RNN_init0.001",
    },
    {
        "arch_group": "two_module_task_routed_sp1",
        "routing": "task_routed",
        "sparsity_label": "1.0",
        "init_scale": 0.01,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_task_routed_nb2_init0.01_nb2_task_routed_sp1_sep_cr_RNN_init0.01",
    },
    {
        "arch_group": "two_module_task_routed_sp1",
        "routing": "task_routed",
        "sparsity_label": "1.0",
        "init_scale": 0.1,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_task_routed_nb2_init0.1_nb2_task_routed_sp1_sep_cr_RNN_init0.1",
    },
    {
        "arch_group": "two_module_task_routed_sp1",
        "routing": "task_routed",
        "sparsity_label": "1.0",
        "init_scale": 1.0,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_task_routed_nb2_nb2_task_routed_sp1_sep_cr_RNN",
    },
    {
        "arch_group": "two_module_task_routed_sp1",
        "routing": "task_routed",
        "sparsity_label": "1.0",
        "init_scale": 2.0,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_task_routed_nb2_init2_nb2_task_routed_sp1.0_sep_cr_RNN_init2",
    },
    {
        "arch_group": "two_module_task_routed_sp05",
        "routing": "task_routed",
        "sparsity_label": "0.5",
        "init_scale": 0.001,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_task_routed_sp05_nb2_init0.001_nb2_task_routed_sp0.5_sep_cr_RNN_init0.001",
    },
    {
        "arch_group": "two_module_task_routed_sp05",
        "routing": "task_routed",
        "sparsity_label": "0.5",
        "init_scale": 0.01,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_task_routed_sp05_nb2_init0.01_nb2_task_routed_sp0.5_sep_cr_RNN_init0.01",
    },
    {
        "arch_group": "two_module_task_routed_sp05",
        "routing": "task_routed",
        "sparsity_label": "0.5",
        "init_scale": 0.1,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_task_routed_sp05_nb2_init0.1_nb2_task_routed_sp0.5_sep_cr_RNN_init0.1",
    },
    {
        "arch_group": "two_module_task_routed_sp05",
        "routing": "task_routed",
        "sparsity_label": "0.5",
        "init_scale": 1.0,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_task_routed_sp05_nb2_nb2_task_routed_sp0.5_sep_cr_RNN",
    },
    {
        "arch_group": "two_module_task_routed_sp05",
        "routing": "task_routed",
        "sparsity_label": "0.5",
        "init_scale": 2.0,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_task_routed_sp05_nb2_init2_nb2_task_routed_sp0.5_sep_cr_RNN_init2",
    },
    {
        "arch_group": "two_module_task_routed_no_comms",
        "routing": "task_routed",
        "sparsity_label": "no_comms",
        "init_scale": 0.001,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_task_routed_no_comms_nb2_init0.001_nb2_task_routed_sp0_sep_cr_RNN_init0.001",
    },
    {
        "arch_group": "two_module_task_routed_no_comms",
        "routing": "task_routed",
        "sparsity_label": "no_comms",
        "init_scale": 0.01,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_task_routed_no_comms_nb2_init0.01_nb2_task_routed_sp0_sep_cr_RNN_init0.01",
    },
    {
        "arch_group": "two_module_task_routed_no_comms",
        "routing": "task_routed",
        "sparsity_label": "no_comms",
        "init_scale": 0.1,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_task_routed_no_comms_nb2_init0.1_nb2_task_routed_sp0_sep_cr_RNN_init0.1",
    },
    {
        "arch_group": "two_module_task_routed_no_comms",
        "routing": "task_routed",
        "sparsity_label": "no_comms",
        "init_scale": 1.0,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_task_routed_no_comms_nb2_nb2_task_routed_sp0_sep_cr_RNN",
    },
    {
        "arch_group": "two_module_task_routed_no_comms",
        "routing": "task_routed",
        "sparsity_label": "no_comms",
        "init_scale": 2.0,
        "comparison_dim_hidden": 25,
        "sim_folder": "two_module_rnn_25_task_routed_no_comms_nb2_init2_nb2_task_routed_sp0_sep_cr_RNN_init2",
    },
    {
        "arch_group": "single_module",
        "routing": "shared",
        "sparsity_label": "single_module",
        "init_scale": 0.001,
        "comparison_dim_hidden": 50,
        "sim_folder": "single_module_rnn_50_nb2_init0.001_nb2_shared_sp1_sep_cr_RNN_init0.001",
    },
    {
        "arch_group": "single_module",
        "routing": "shared",
        "sparsity_label": "single_module",
        "init_scale": 0.01,
        "comparison_dim_hidden": 50,
        "sim_folder": "single_module_rnn_50_nb2_init0.01_nb2_shared_sp1_sep_cr_RNN_init0.01",
    },
    {
        "arch_group": "single_module",
        "routing": "shared",
        "sparsity_label": "single_module",
        "init_scale": 0.1,
        "comparison_dim_hidden": 50,
        "sim_folder": "single_module_rnn_50_nb2_init0.1_nb2_shared_sp1_sep_cr_RNN_init0.1",
    },
    {
        "arch_group": "single_module",
        "routing": "shared",
        "sparsity_label": "single_module",
        "init_scale": 1.0,
        "comparison_dim_hidden": 50,
        "sim_folder": "single_module_rnn_50_nb2_nb2_shared_sp1_sep_cr_RNN",
    },
    {
        "arch_group": "single_module",
        "routing": "shared",
        "sparsity_label": "single_module",
        "init_scale": 2.0,
        "comparison_dim_hidden": 50,
        "sim_folder": "single_module_rnn_50_nb2_init2_nb2_shared_sp1_sep_cr_RNN_init2",
    },
]

targets = pd.DataFrame(TARGET_RUNS)
targets

                         arch_group      routing sparsity_label  init_scale  comparison_dim_hidden                                         sim_folder
0             two_module_shared_sp1       shared            1.0       0.001                     25  two_module_rnn_25_nb2_init0.001_nb2_shared_sp1...
1             two_module_shared_sp1       shared            1.0       0.010                     25  two_module_rnn_25_nb2_init0.01_nb2_shared_sp1....
2             two_module_shared_sp1       shared            1.0       0.100                     25  two_module_rnn_25_nb2_init0.1_nb2_shared_sp1.0...
3             two_module_shared_sp1       shared            1.0       1.000                     25  two_module_rnn_25_nb2_nb2_shared_sp1.0_sep_cr_RNN
4             two_module_shared_sp1       shared            1.0       2.000                     25  two_module_rnn_25_nb2_init2_nb2_shared_sp1.0_s...
5            two_module_shared_sp05       shared            0.5       0.001                     25  two_module_rnn_25_sp05_nb2_init0.001_nb2_share...
6            two_module_shared_sp05       shared            0.5       0.010                     25  two_module_rnn_25_sp05_nb2_init0.01_nb2_shared...
7            two_module_shared_sp05       shared            0.5       0.100                     25  two_module_rnn_25_sp05_nb2_init0.1_nb2_shared_...
8            two_module_shared_sp05       shared            0.5       1.000                     25  two_module_rnn_25_sp05_nb2_nb2_shared_sp0.5_se...
9            two_module_shared_sp05       shared            0.5       2.000                     25  two_module_rnn_25_sp05_nb2_init2_nb2_shared_sp...
10       two_module_shared_no_comms       shared       no_comms       0.001                     25  two_module_rnn_25_no_comms_nb2_init0.001_nb2_s...
11       two_module_shared_no_comms       shared       no_comms       0.010                     25  two_module_rnn_25_no_comms_nb2_init0.01_nb2_sh...
12       two_module_shared_no_comms       shared       no_comms       0.100                     25  two_module_rnn_25_no_comms_nb2_init0.1_nb2_sha...
13       two_module_shared_no_comms       shared       no_comms       1.000                     25  two_module_rnn_25_no_comms_nb2_nb2_shared_sp0_...
14       two_module_shared_no_comms       shared       no_comms       2.000                     25  two_module_rnn_25_no_comms_nb2_init2_nb2_share...
15       two_module_task_routed_sp1  task_routed            1.0       0.001                     25  two_module_rnn_25_task_routed_nb2_init0.001_nb...
16       two_module_task_routed_sp1  task_routed            1.0       0.010                     25  two_module_rnn_25_task_routed_nb2_init0.01_nb2...
17       two_module_task_routed_sp1  task_routed            1.0       0.100                     25  two_module_rnn_25_task_routed_nb2_init0.1_nb2_...
18       two_module_task_routed_sp1  task_routed            1.0       1.000                     25  two_module_rnn_25_task_routed_nb2_nb2_task_rou...
19       two_module_task_routed_sp1  task_routed            1.0       2.000                     25  two_module_rnn_25_task_routed_nb2_init2_nb2_ta...
20      two_module_task_routed_sp05  task_routed            0.5       0.001                     25  two_module_rnn_25_task_routed_sp05_nb2_init0.0...
21      two_module_task_routed_sp05  task_routed            0.5       0.010                     25  two_module_rnn_25_task_routed_sp05_nb2_init0.0...
22      two_module_task_routed_sp05  task_routed            0.5       0.100                     25  two_module_rnn_25_task_routed_sp05_nb2_init0.1...
23      two_module_task_routed_sp05  task_routed            0.5       1.000                     25  two_module_rnn_25_task_routed_sp05_nb2_nb2_tas...
24      two_module_task_routed_sp05  task_routed            0.5       2.000                     25  two_module_rnn_25_task_routed_sp05_nb2_init2_n...
25  two_module_task_routed_no_comms  task_routed       no_comms       0.001                     25  two_module_rnn_25_task_routed_no_comms_nb2_ini...
26  two_module_task_routed_no_comms  task_routed       no_comms       0.010                     25  two_module_rnn_25_task_routed_no_comms_nb2_ini...
27  two_module_task_routed_no_comms  task_routed       no_comms       0.100                     25  two_module_rnn_25_task_routed_no_comms_nb2_ini...
28  two_module_task_routed_no_comms  task_routed       no_comms       1.000                     25  two_module_rnn_25_task_routed_no_comms_nb2_nb2...
29  two_module_task_routed_no_comms  task_routed       no_comms       2.000                     25  two_module_rnn_25_task_routed_no_comms_nb2_ini...
30                    single_module       shared  single_module       0.001                     50  single_module_rnn_50_nb2_init0.001_nb2_shared_...
31                    single_module       shared  single_module       0.010                     50  single_module_rnn_50_nb2_init0.01_nb2_shared_s...
32                    single_module       shared  single_module       0.100                     50  single_module_rnn_50_nb2_init0.1_nb2_shared_sp...
33                    single_module       shared  single_module       1.000                     50  single_module_rnn_50_nb2_nb2_shared_sp1_sep_cr...
34                    single_module       shared  single_module       2.000                     50  single_module_rnn_50_nb2_init2_nb2_shared_sp1_...

## 1. Audit whether the fitting completed correctly

A run is considered successfully completed here if:

- the simulation folder exists
- the folder contains participant `.npz` files
- the generated `*_vonmises_fits.csv` exists
- the CSV has the expected participant count and required columns

In [124]:
required_fit_cols = {
    "participant", "condition",
    "A_weight_A1", "A_weight_B", "A_weight_A2",
    "kappa_A1", "kappa_B", "kappa_A2",
}

audit_rows = []
for row in TARGET_RUNS:
    sim_folder = row["sim_folder"]
    sim_dir = data_root / sim_folder
    fit_csv = data_root / f"{sim_folder}_vonmises_fits.csv"
    npz_files = sorted(sim_dir.glob("*.npz")) if sim_dir.exists() else []

    info = dict(row)
    info["sim_dir_exists"] = sim_dir.exists()
    info["n_npz_files"] = len(npz_files)
    info["fit_csv_exists"] = fit_csv.exists()
    info["fit_csv_path"] = str(fit_csv)

    if fit_csv.exists():
        fit_df = pd.read_csv(fit_csv)
        info["n_fit_rows"] = len(fit_df)
        info["n_fit_participants"] = fit_df["participant"].nunique() if "participant" in fit_df else np.nan
        info["fit_conditions"] = sorted(fit_df["condition"].dropna().unique().tolist()) if "condition" in fit_df else []
        info["missing_required_cols"] = sorted(required_fit_cols.difference(fit_df.columns))
        info["fit_complete"] = (
            len(npz_files) > 0
            and len(required_fit_cols.difference(fit_df.columns)) == 0
            and fit_df["participant"].nunique() > 0
        )
    else:
        info["n_fit_rows"] = np.nan
        info["n_fit_participants"] = np.nan
        info["fit_conditions"] = []
        info["missing_required_cols"] = []
        info["fit_complete"] = False

    audit_rows.append(info)

audit_df = pd.DataFrame(audit_rows)
audit_df

,arch_group,routing,sparsity_label,init_scale,comparison_dim_hidden,sim_folder,sim_dir_exists,n_npz_files,fit_csv_exists,fit_csv_path,n_fit_rows,n_fit_participants,fit_conditions,missing_required_cols,fit_complete
0,two_module_shared_sp1,shared,1.0,0.001,25,two_module_rnn_25_nb2_init0.001_nb2_shared_sp1...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
1,two_module_shared_sp1,shared,1.0,0.010,25,two_module_rnn_25_nb2_init0.01_nb2_shared_sp1....,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
2,two_module_shared_sp1,shared,1.0,0.100,25,two_module_rnn_25_nb2_init0.1_nb2_shared_sp1.0...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
3,two_module_shared_sp1,shared,1.0,1.000,25,two_module_rnn_25_nb2_nb2_shared_sp1.0_sep_cr_RNN,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
4,two_module_shared_sp1,shared,1.0,2.000,25,two_module_rnn_25_nb2_init2_nb2_shared_sp1.0_s...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
5,two_module_shared_sp05,shared,0.5,0.001,25,two_module_rnn_25_sp05_nb2_init0.001_nb2_share...,True,202,False,/home/kat/workspace/Structure-Function-Analysi...,NaN,NaN,[],[],False
6,two_module_shared_sp05,shared,0.5,0.010,25,two_module_rnn_25_sp05_nb2_init0.01_nb2_shared...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
7,two_module_shared_sp05,shared,0.5,0.100,25,two_module_rnn_25_sp05_nb2_init0.1_nb2_shared_...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
8,two_module_shared_sp05,shared,0.5,1.000,25,two_module_rnn_25_sp05_nb2_nb2_shared_sp0.5_se...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
9,two_module_shared_sp05,shared,0.5,2.000,25,two_module_rnn_25_sp05_nb2_init2_nb2_shared_sp...,True,248,False,/home/kat/workspace/Structure-Function-Analysi...,NaN,NaN,[],[],False
10,two_module_shared_no_comms,shared,no_comms,0.001,25,two_module_rnn_25_no_comms_nb2_init0.001_nb2_s...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
11,two_module_shared_no_comms,shared,no_comms,0.010,25,two_module_rnn_25_no_comms_nb2_init0.01_nb2_sh...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
12,two_module_shared_no_comms,shared,no_comms,0.100,25,two_module_rnn_25_no_comms_nb2_init0.1_nb2_sha...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
13,two_module_shared_no_comms,shared,no_comms,1.000,25,two_module_rnn_25_no_comms_nb2_nb2_shared_sp0_...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
14,two_module_shared_no_comms,shared,no_comms,2.000,25,two_module_rnn_25_no_comms_nb2_init2_nb2_share...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
15,two_module_task_routed_sp1,task_routed,1.0,0.001,25,two_module_rnn_25_task_routed_nb2_init0.001_nb...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
16,two_module_task_routed_sp1,task_routed,1.0,0.010,25,two_module_rnn_25_task_routed_nb2_init0.01_nb2...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
17,two_module_task_routed_sp1,task_routed,1.0,0.100,25,two_module_rnn_25_task_routed_nb2_init0.1_nb2_...,True,186,True,/home/kat/workspace/Structure-Function-Analysi...,125.0,125.0,"[far, near]",[],True
18,two_module_task_routed_sp1,task_routed,1.0,1.000,25,two_module_rnn_25_task_routed_nb2_nb2_task_rou...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
19,two_module_task_routed_sp1,task_routed,1.0,2.000,25,two_module_rnn_25_task_routed_nb2_init2_nb2_ta...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
20,two_module_task_routed_sp05,task_routed,0.5,0.001,25,two_module_rnn_25_task_routed_sp05_nb2_init0.0...,True,200,False,/home/kat/workspace/Structure-Function-Analysi...,NaN,NaN,[],[],False
21,two_module_task_routed_sp05,task_routed,0.5,0.010,25,two_module_rnn_25_task_routed_sp05_nb2_init0.0...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
22,two_module_task_routed_sp05,task_routed,0.5,0.100,25,two_module_rnn_25_task_routed_sp05_nb2_init0.1...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
23,two_module_task_routed_sp05,task_routed,0.5,1.000,25,two_module_rnn_25_task_routed_sp05_nb2_nb2_tas...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
24,two_module_task_routed_sp05,task_routed,0.5,2.000,25,two_module_rnn_25_task_routed_sp05_nb2_init2_n...,True,234,False,/home/kat/workspace/Structure-Function-Analysi...,NaN,NaN,[],[],False
25,two_module_task_routed_no_comms,task_routed,no_comms,0.001,25,two_module_rnn_25_task_routed_no_comms_nb2_ini...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
26,two_module_task_routed_no_comms,task_routed,no_comms,0.010,25,two_module_rnn_25_task_routed_no_comms_nb2_ini...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
27,two_module_task_routed_no_comms,task_routed,no_comms,0.100,25,two_module_rnn_25_task_routed_no_comms_nb2_ini...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
28,two_module_task_routed_no_comms,task_routed,no_comms,1.000,25,two_module_rnn_25_task_routed_no_comms_nb2_nb2...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
29,two_module_task_routed_no_comms,task_routed,no_comms,2.000,25,two_module_rnn_25_task_routed_no_comms_nb2_ini...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
30,single_module,shared,single_module,0.001,50,single_module_rnn_50_nb2_init0.001_nb2_shared_...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
31,single_module,shared,single_module,0.010,50,single_module_rnn_50_nb2_init0.01_nb2_shared_s...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
32,single_module,shared,single_module,0.100,50,single_module_rnn_50_nb2_init0.1_nb2_shared_sp...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
33,single_module,shared,single_module,1.000,50,single_module_rnn_50_nb2_nb2_shared_sp1_sep_cr...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True
34,single_module,shared,single_module,2.000,50,single_module_rnn_50_nb2_init2_nb2_shared_sp1_...,True,305,True,/home/kat/workspace/Structure-Function-Analysi...,202.0,202.0,"[far, near]",[],True

In [125]:
summary_cols = [
    "arch_group", "routing", "sparsity_label", "init_scale",
    "n_npz_files", "fit_csv_exists", "n_fit_participants",
    "fit_conditions", "missing_required_cols", "fit_complete",
]
audit_df[summary_cols].sort_values(["arch_group", "init_scale"])

                         arch_group      routing sparsity_label  init_scale  n_npz_files  fit_csv_exists  n_fit_participants fit_conditions missing_required_cols  fit_complete
30                    single_module       shared  single_module       0.001          305            True               202.0    [far, near]                    []          True
31                    single_module       shared  single_module       0.010          305            True               202.0    [far, near]                    []          True
32                    single_module       shared  single_module       0.100          305            True               202.0    [far, near]                    []          True
33                    single_module       shared  single_module       1.000          305            True               202.0    [far, near]                    []          True
34                    single_module       shared  single_module       2.000          305            True               202.0    [far, near]                    []          True
10       two_module_shared_no_comms       shared       no_comms       0.001          305            True               202.0    [far, near]                    []          True
11       two_module_shared_no_comms       shared       no_comms       0.010          305            True               202.0    [far, near]                    []          True
12       two_module_shared_no_comms       shared       no_comms       0.100          305            True               202.0    [far, near]                    []          True
13       two_module_shared_no_comms       shared       no_comms       1.000          305            True               202.0    [far, near]                    []          True
14       two_module_shared_no_comms       shared       no_comms       2.000          305            True               202.0    [far, near]                    []          True
5            two_module_shared_sp05       shared            0.5       0.001          202           False                 NaN             []                    []         False
6            two_module_shared_sp05       shared            0.5       0.010          305            True               202.0    [far, near]                    []          True
7            two_module_shared_sp05       shared            0.5       0.100          305            True               202.0    [far, near]                    []          True
8            two_module_shared_sp05       shared            0.5       1.000          305            True               202.0    [far, near]                    []          True
9            two_module_shared_sp05       shared            0.5       2.000          248           False                 NaN             []                    []         False
0             two_module_shared_sp1       shared            1.0       0.001          305            True               202.0    [far, near]                    []          True
1             two_module_shared_sp1       shared            1.0       0.010          305            True               202.0    [far, near]                    []          True
2             two_module_shared_sp1       shared            1.0       0.100          305            True               202.0    [far, near]                    []          True
3             two_module_shared_sp1       shared            1.0       1.000          305            True               202.0    [far, near]                    []          True
4             two_module_shared_sp1       shared            1.0       2.000          305            True               202.0    [far, near]                    []          True
25  two_module_task_routed_no_comms  task_routed       no_comms       0.001          305            True               202.0    [far, near]                    []          True
26  two_module_task_routed_no_comms  task_routed       no_comms       0.010          305            True               202.0    [far, near]                    []          True
27  two_module_task_routed_no_comms  task_routed       no_comms       0.100          305            True               202.0    [far, near]                    []          True
28  two_module_task_routed_no_comms  task_routed       no_comms       1.000          305            True               202.0    [far, near]                    []          True
29  two_module_task_routed_no_comms  task_routed       no_comms       2.000          305            True               202.0    [far, near]                    []          True
20      two_module_task_routed_sp05  task_routed            0.5       0.001          200           False                 NaN             []                    []         False
21      two_module_task_routed_sp05  task_routed            0.5       0.010          305            True               202.0    [far, near]                    []          True
22      two_module_task_routed_sp05  task_routed            0.5       0.100          305            True               202.0    [far, near]                    []          True
23      two_module_task_routed_sp05  task_routed            0.5       1.000          305            True               202.0    [far, near]                    []          True
24      two_module_task_routed_sp05  task_routed            0.5       2.000          234           False                 NaN             []                    []         False
15       two_module_task_routed_sp1  task_routed            1.0       0.001          305            True               202.0    [far, near]                    []          True
16       two_module_task_routed_sp1  task_routed            1.0       0.010          305            True               202.0    [far, near]                    []          True
17       two_module_task_routed_sp1  task_routed            1.0       0.100          186            True               125.0    [far, near]                    []          True
18       two_module_task_routed_sp1  task_routed            1.0       1.000          305            True               202.0    [far, near]                    []          True
19       two_module_task_routed_sp1  task_routed            1.0       2.000          305            True               202.0    [far, near]                    []          True

## 2. Load completed fit CSVs

Each fit CSV contains participant-level von Mises estimates. The key paper-faithful quantity is the A2 mixture weight:

- `A_weight_A2`: estimated probability mass on Rule A during A2
- `interference = 1 - A_weight_A2`: estimated Rule-B usage during A2

In [126]:
fit_frames = []
for row in TARGET_RUNS:
    fit_csv = data_root / f"{row['sim_folder']}_vonmises_fits.csv"
    if not fit_csv.exists():
        continue
    df = pd.read_csv(fit_csv).copy()
    for key, value in row.items():
        df[key] = value
    fit_frames.append(df)

fits = pd.concat(fit_frames, ignore_index=True) if fit_frames else pd.DataFrame()
fits.shape

(6185, 14)

In [127]:
if fits.empty:
    print("No fit CSVs found yet.")
else:
    display(fits.head())

,participant,condition,A_weight_A1,kappa_A1,A_weight_B,kappa_B,A_weight_A2,kappa_A2,arch_group,routing,sparsity_label,init_scale,comparison_dim_hidden,sim_folder
0,sim_study2_near_sub38,near,0.956597,23.417899,0.10000,927.085537,0.000003,58.557561,two_module_shared_sp1,shared,1.0,0.001,25,two_module_rnn_25_nb2_init0.001_nb2_shared_sp1...
1,sim_study1_near_sub50,near,0.763146,7.429183,0.10000,696.735500,0.000020,53.431221,two_module_shared_sp1,shared,1.0,0.001,25,two_module_rnn_25_nb2_init0.001_nb2_shared_sp1...
2,sim_study2_near_sub66,near,0.656099,3.460328,0.09948,430.402809,0.000080,41.507753,two_module_shared_sp1,shared,1.0,0.001,25,two_module_rnn_25_nb2_init0.001_nb2_shared_sp1...
3,sim_study1_near_sub47,near,0.966179,1.950195,0.10000,503.363211,0.000048,42.370741,two_module_shared_sp1,shared,1.0,0.001,25,two_module_rnn_25_nb2_init0.001_nb2_shared_sp1...
4,sim_study2_near_sub30,near,0.996489,4.781103,0.08312,283.693228,0.000007,54.176539,two_module_shared_sp1,shared,1.0,0.001,25,two_module_rnn_25_nb2_init0.001_nb2_shared_sp1...

## 3. Compute paper-faithful interference

For each participant and condition:

- `interference = 1 - A_weight_A2`

This notebook keeps `same` visible if present in the fit CSV, but the primary interpretation should focus on `near` and `far`.

In [128]:
if fits.empty:
    interference_df = pd.DataFrame()
else:
    interference_df = fits.copy()
    interference_df["interference"] = 1.0 - interference_df["A_weight_A2"]
    interference_df["interference_clipped"] = interference_df["interference"].clip(0.0, 1.0)

interference_df.head() if not interference_df.empty else interference_df

,participant,condition,A_weight_A1,kappa_A1,A_weight_B,kappa_B,A_weight_A2,kappa_A2,arch_group,routing,sparsity_label,init_scale,comparison_dim_hidden,sim_folder,interference,interference_clipped
0,sim_study2_near_sub38,near,0.956597,23.417899,0.10000,927.085537,0.000003,58.557561,two_module_shared_sp1,shared,1.0,0.001,25,two_module_rnn_25_nb2_init0.001_nb2_shared_sp1...,0.999997,0.999997
1,sim_study1_near_sub50,near,0.763146,7.429183,0.10000,696.735500,0.000020,53.431221,two_module_shared_sp1,shared,1.0,0.001,25,two_module_rnn_25_nb2_init0.001_nb2_shared_sp1...,0.999980,0.999980
2,sim_study2_near_sub66,near,0.656099,3.460328,0.09948,430.402809,0.000080,41.507753,two_module_shared_sp1,shared,1.0,0.001,25,two_module_rnn_25_nb2_init0.001_nb2_shared_sp1...,0.999920,0.999920
3,sim_study1_near_sub47,near,0.966179,1.950195,0.10000,503.363211,0.000048,42.370741,two_module_shared_sp1,shared,1.0,0.001,25,two_module_rnn_25_nb2_init0.001_nb2_shared_sp1...,0.999952,0.999952
4,sim_study2_near_sub30,near,0.996489,4.781103,0.08312,283.693228,0.000007,54.176539,two_module_shared_sp1,shared,1.0,0.001,25,two_module_rnn_25_nb2_init0.001_nb2_shared_sp1...,0.999993,0.999993

In [129]:
if interference_df.empty:
    print("No completed fits available.")
else:
    near_far = interference_df[interference_df["condition"].isin(["near", "far"])].copy()
    summary = (
        near_far.groupby(["arch_group", "routing", "sparsity_label", "init_scale", "condition"], observed=True)
        .agg(
            n=("participant", "nunique"),
            A_weight_A2_mean=("A_weight_A2", "mean"),
            A_weight_A2_sem=("A_weight_A2", "sem"),
            interference_mean=("interference", "mean"),
            interference_sem=("interference", "sem"),
            kappa_A2_mean=("kappa_A2", "mean"),
            kappa_A2_sem=("kappa_A2", "sem"),
        )
        .reset_index()
        .sort_values(["arch_group", "init_scale", "condition"])
    )
    display(summary)

                         arch_group      routing sparsity_label  init_scale condition    n  A_weight_A2_mean  A_weight_A2_sem  interference_mean  interference_sem  kappa_A2_mean  kappa_A2_sem
0                     single_module       shared  single_module       0.001       far  101          0.392826     2.700984e-02       6.071742e-01      2.700984e-02       0.943797      0.082341
1                     single_module       shared  single_module       0.001      near  101          0.000017     3.867943e-06       9.999835e-01      3.867943e-06      55.268888      0.606493
2                     single_module       shared  single_module       0.010       far  101          0.999807     1.663275e-04       1.928849e-04      1.663275e-04      27.093603      6.758280
3                     single_module       shared  single_module       0.010      near  101          0.000018     4.274738e-06       9.999822e-01      4.274738e-06      55.014948      0.605364
4                     single_module       shared  single_module       0.100       far  101          1.000000     0.000000e+00       0.000000e+00      0.000000e+00     128.905907     11.675895
5                     single_module       shared  single_module       0.100      near  101          0.000105     4.719924e-05       9.998948e-01      4.719924e-05      50.610753      0.602771
6                     single_module       shared  single_module       1.000       far  101          0.938435     7.783587e-03       6.156523e-02      7.783587e-03      13.905894      1.751525
7                     single_module       shared  single_module       1.000      near  101          0.835181     1.890222e-02       1.648186e-01      1.890222e-02      26.870449      1.460477
8                     single_module       shared  single_module       2.000       far  101          0.933902     8.638196e-03       6.609793e-02      8.638196e-03       5.008628      0.395068
9                     single_module       shared  single_module       2.000      near  101          0.781788     2.637900e-02       2.182122e-01      2.637900e-02       4.610208      0.797289
10       two_module_shared_no_comms       shared       no_comms       0.001       far  101          0.936000     1.086526e-02       6.400012e-02      1.086526e-02       3.211870      0.502680
11       two_module_shared_no_comms       shared       no_comms       0.001      near  101          0.000308     1.007969e-04       9.996920e-01      1.007969e-04      48.416747      0.715744
12       two_module_shared_no_comms       shared       no_comms       0.010       far  101          1.000000     0.000000e+00       0.000000e+00      0.000000e+00      45.690088      6.234206
13       two_module_shared_no_comms       shared       no_comms       0.010      near  101          0.000313     1.023550e-04       9.996873e-01      1.023550e-04      48.197924      0.711347
14       two_module_shared_no_comms       shared       no_comms       0.100       far  101          1.000000     0.000000e+00       0.000000e+00      0.000000e+00     131.951340     11.701075
15       two_module_shared_no_comms       shared       no_comms       0.100      near  101          0.000466     1.289987e-04       9.995344e-01      1.289987e-04      44.152236      0.666818
16       two_module_shared_no_comms       shared       no_comms       1.000       far  101          0.927290     7.940477e-03       7.270983e-02      7.940477e-03      13.612359      2.448788
17       two_module_shared_no_comms       shared       no_comms       1.000      near  101          0.840962     1.905670e-02       1.590383e-01      1.905670e-02      34.125368      2.526483
18       two_module_shared_no_comms       shared       no_comms       2.000       far  101          0.918531     7.928504e-03       8.146903e-02      7.928504e-03       4.639719      0.460945
19       two_module_shared_no_comms       shared       no_comms       2.000      near  101          0.795783     2.394106e-02       2.042170e-01      2.394106e-02       5.238666      0.731159
20           two_module_shared_sp05       shared            0.5       0.010       far  101          1.000000     4.715456e-17       5.716000e-17      4.654538e-17      35.329367      5.117824
21           two_module_shared_sp05       shared            0.5       0.010      near  101          0.000261     8.260047e-05       9.997393e-01      8.260047e-05      49.582335      0.734960
22           two_module_shared_sp05       shared            0.5       0.100       far  101          1.000000     0.000000e+00       0.000000e+00      0.000000e+00     128.081728     11.103710
23           two_module_shared_sp05       shared            0.5       0.100      near  101          0.000328     8.504596e-05       9.996717e-01      8.504596e-05      45.603316      0.690058
24           two_module_shared_sp05       shared            0.5       1.000       far  101          0.926141     7.887921e-03       7.385885e-02      7.887921e-03      12.153298      1.516850
25           two_module_shared_sp05       shared            0.5       1.000      near  101          0.834628     1.940390e-02       1.653719e-01      1.940390e-02      33.215345      2.498154
26            two_module_shared_sp1       shared            1.0       0.001       far  101          0.409029     2.787464e-02       5.909707e-01      2.787464e-02       0.993991      0.103328
27            two_module_shared_sp1       shared            1.0       0.001      near  101          0.000208     6.309189e-05       9.997917e-01      6.309189e-05      51.076082      0.757718
28            two_module_shared_sp1       shared            1.0       0.010       far  101          1.000000     3.857006e-07       3.857025e-07      3.857006e-07      28.656755      5.823973
29            two_module_shared_sp1       shared            1.0       0.010      near  101          0.000201     6.035358e-05       9.997989e-01      6.035358e-05      50.851846      0.753423
30            two_module_shared_sp1       shared            1.0       0.100       far  101          1.000000     0.000000e+00       0.000000e+00      0.000000e+00     122.842239     10.566093
31            two_module_shared_sp1       shared            1.0       0.100      near  101          0.000258     6.624677e-05       9.997423e-01      6.624677e-05      46.986370      0.708457
32            two_module_shared_sp1       shared            1.0       1.000       far  101          0.935071     7.924384e-03       6.492914e-02      7.924384e-03      13.655066      2.206798
33            two_module_shared_sp1       shared            1.0       1.000      near  101          0.820967     2.109941e-02       1.790327e-01      2.109941e-02      33.365091      2.669403
34            two_module_shared_sp1       shared            1.0       2.000       far  101          0.912657     9.168232e-03       8.734253e-02      9.168232e-03       4.577063      0.468802
35            two_module_shared_sp1       shared            1.0       2.000      near  101          0.740296     2.913659e-02       2.597042e-01      2.913659e-02       5.444610      0.914859
36  two_module_task_routed_no_comms  task_routed       no_comms       0.001       far  101          0.895845     7.760741e-03       1.041548e-01      7.760741e-03      22.032741      3.118352
37  two_module_task_routed_no_comms  task_routed       no_comms       0.001      near  101          0.919186     9.487125e-03       8.081448e-02      9.487125e-03      10.885118      2.281618
38  two_module_task_routed_no_comms  task_routed       no_comms       0.010       far  101          0.896111     7.777105e-03       1.038889e-01      7.777105e-03      22.060880      3.127776
39  two_module_task_routed_no_comms  task_routed       no_comms       0.010      near  101          0.918916     9.533366e-03       8.108429e-02      9.533366e-03      10.890960      2.282557
40  two_module_task_routed_no_comms  task_routed       no_comms       0.100       far  101          0.893688     7.802122e-03       1.063122e-01      7.802122e-03      23.231803      3.433592
41  two_module_task_routed_no_comms  task_routed       no_comms       0.100      near  101          0.917019     9.455564e-03       8.298095e-02      9.455564e-03      11.203495      2.356960
42  two_module_task_routed_no_comms  task_routed       no_comms       1.000       far  101          0.923574     8.085055e-03       7.642649e-02      8.085055e-03      18.231039      2.334968
43  two_module_task_routed_no_comms  task_routed       no_comms       1.000      near  101          0.907662     1.186339e-02       9.233793e-02      1.186339e-02      11.160316      1.831716
44  two_module_task_routed_no_comms  task_routed       no_comms       2.000       far  101          0.904785     9.979805e-03       9.521527e-02      9.979805e-03       3.460848      0.223865
45  two_module_task_routed_no_comms  task_routed       no_comms       2.000      near  101          0.726314     2.920001e-02       2.736864e-01      2.920001e-02       3.006003      0.482213
46      two_module_task_routed_sp05  task_routed            0.5       0.010       far  101          0.896111     7.777108e-03       1.038889e-01      7.777108e-03      22.060887      3.127780
47      two_module_task_routed_sp05  task_routed            0.5       0.010      near  101          0.918916     9.533323e-03       8.108396e-02      9.533323e-03      10.890952      2.282556
48      two_module_task_routed_sp05  task_routed            0.5       0.100       far  101          0.893685     7.802055e-03       1.063147e-01      7.802055e-03      23.232251      3.433773
49      two_module_task_routed_sp05  task_routed            0.5       0.100      near  101          0.917018     9.455649e-03       8.298219e-02      9.455649e-03      11.204045      2.357448
50      two_module_task_routed_sp05  task_routed            0.5       1.000       far  101          0.925155     8.105819e-03       7.484470e-02      8.105819e-03      17.817687      2.512425
51      two_module_task_routed_sp05  task_routed            0.5       1.000      near  101          0.909633     1.177187e-02       9.036749e-02      1.177187e-02      11.279064      1.881025
52       two_module_task_routed_sp1  task_routed            1.0       0.001       far  101          0.895845     7.760743e-03       1.041548e-01      7.760743e-03      22.032733      3.118358
53       two_module_task_routed_sp1  task_routed            1.0       0.001      near  101          0.919185     9.487120e-03       8.081450e-02      9.487120e-03      10.885093      2.281609
54       two_module_task_routed_sp1  task_routed            1.0       0.010       far  101          0.896111     7.777104e-03       1.038889e-01      7.777104e-03      22.060896      3.127780
55       two_module_task_routed_sp1  task_routed            1.0       0.010      near  101          0.918916     9.533371e-03       8.108422e-02      9.533371e-03      10.890955      2.282559
56       two_module_task_routed_sp1  task_routed            1.0       0.100       far   56          0.896410     1.061456e-02       1.035901e-01      1.061456e-02      17.024954      2.706792
57       two_module_task_routed_sp1  task_routed            1.0       0.100      near   69          0.919396     1.179456e-02       8.060382e-02      1.179456e-02      10.536769      2.947226
58       two_module_task_routed_sp1  task_routed            1.0       1.000       far  101          0.925041     8.063589e-03       7.495894e-02      8.063589e-03      18.323508      2.586852
59       two_module_task_routed_sp1  task_routed            1.0       1.000      near  101          0.909932     1.172212e-02       9.006799e-02      1.172212e-02      11.738229      2.009613
60       two_module_task_routed_sp1  task_routed            1.0       2.000       far  101          0.921610     8.268001e-03       7.839031e-02      8.268001e-03       3.765494      0.262887
61       two_module_task_routed_sp1  task_routed            1.0       2.000      near  101          0.718013     2.997808e-02       2.819873e-01      2.997808e-02       2.926358      0.428554

## 4. Sanity checks

Useful basic checks:

- `A_weight_A2` should usually lie near `[0, 1]`
- `interference = 1 - A_weight_A2` should usually lie near `[0, 1]`
- `near` and `far` should both be present for the ANN runs
- participant counts should be roughly consistent across compared cells

In [130]:
if interference_df.empty:
    print("No completed fits available.")
else:
    checks = (
        interference_df.groupby(["arch_group", "init_scale", "condition"], observed=True)
        .agg(
            n=("participant", "nunique"),
            min_A_weight_A2=("A_weight_A2", "min"),
            max_A_weight_A2=("A_weight_A2", "max"),
            min_interference=("interference", "min"),
            max_interference=("interference", "max"),
        )
        .reset_index()
        .sort_values(["arch_group", "init_scale", "condition"])
    )
    display(checks)

                         arch_group  init_scale condition    n  min_A_weight_A2  max_A_weight_A2  min_interference  max_interference
0                     single_module       0.001       far  101     6.407656e-02         0.945947      5.405253e-02      9.359234e-01
1                     single_module       0.001      near  101     2.778062e-07         0.000255      9.997452e-01      9.999997e-01
2                     single_module       0.010       far  101     9.834206e-01         1.000000      0.000000e+00      1.657940e-02
3                     single_module       0.010      near  101     2.957274e-07         0.000252      9.997485e-01      9.999997e-01
4                     single_module       0.100       far  101     1.000000e+00         1.000000      0.000000e+00      0.000000e+00
5                     single_module       0.100      near  101     3.151398e-07         0.003490      9.965099e-01      9.999997e-01
6                     single_module       1.000       far  101     8.333174e-01         1.000000      0.000000e+00      1.666826e-01
7                     single_module       1.000      near  101     2.186414e-01         0.999966      3.389203e-05      7.813586e-01
8                     single_module       2.000       far  101     6.553369e-01         1.000000      0.000000e+00      3.446631e-01
9                     single_module       2.000      near  101     8.227528e-02         0.999345      6.545605e-04      9.177247e-01
10       two_module_shared_no_comms       0.001       far  101     3.485521e-01         1.000000      0.000000e+00      6.514479e-01
11       two_module_shared_no_comms       0.001      near  101     3.411366e-07         0.005975      9.940249e-01      9.999997e-01
12       two_module_shared_no_comms       0.010       far  101     1.000000e+00         1.000000      0.000000e+00      0.000000e+00
13       two_module_shared_no_comms       0.010      near  101     3.529429e-07         0.006043      9.939573e-01      9.999996e-01
14       two_module_shared_no_comms       0.100       far  101     1.000000e+00         1.000000      0.000000e+00      0.000000e+00
15       two_module_shared_no_comms       0.100      near  101     1.139339e-06         0.007232      9.927681e-01      9.999989e-01
16       two_module_shared_no_comms       1.000       far  101     8.333333e-01         1.000000      0.000000e+00      1.666667e-01
17       two_module_shared_no_comms       1.000      near  101     2.716198e-01         1.000000      5.109305e-08      7.283802e-01
18       two_module_shared_no_comms       2.000       far  101     7.628847e-01         1.000000      0.000000e+00      2.371153e-01
19       two_module_shared_no_comms       2.000      near  101     8.957321e-02         0.999447      5.533181e-04      9.104268e-01
20           two_module_shared_sp05       0.010       far  101     1.000000e+00         1.000000      0.000000e+00      4.551914e-15
21           two_module_shared_sp05       0.010      near  101     2.654546e-07         0.005777      9.942227e-01      9.999997e-01
22           two_module_shared_sp05       0.100       far  101     1.000000e+00         1.000000      0.000000e+00      0.000000e+00
23           two_module_shared_sp05       0.100      near  101     7.274371e-07         0.004973      9.950266e-01      9.999993e-01
24           two_module_shared_sp05       1.000       far  101     8.333333e-01         1.000000      0.000000e+00      1.666667e-01
25           two_module_shared_sp05       1.000      near  101     2.173822e-01         0.999999      5.628365e-07      7.826178e-01
26            two_module_shared_sp1       0.001       far  101     1.278010e-14         0.931930      6.806952e-02      1.000000e+00
27            two_module_shared_sp1       0.001      near  101     1.989269e-07         0.003412      9.965878e-01      9.999998e-01
28            two_module_shared_sp1       0.010       far  101     9.999610e-01         1.000000      0.000000e+00      3.895576e-05
29            two_module_shared_sp1       0.010      near  101     1.806189e-07         0.003534      9.964658e-01      9.999998e-01
30            two_module_shared_sp1       0.100       far  101     1.000000e+00         1.000000      0.000000e+00      0.000000e+00
31            two_module_shared_sp1       0.100      near  101     4.957513e-07         0.003558      9.964417e-01      9.999995e-01
32            two_module_shared_sp1       1.000       far  101     8.333333e-01         1.000000      0.000000e+00      1.666667e-01
33            two_module_shared_sp1       1.000      near  101     2.525561e-01         1.000000      1.379743e-07      7.474439e-01
34            two_module_shared_sp1       2.000       far  101     6.666651e-01         1.000000      0.000000e+00      3.333349e-01
35            two_module_shared_sp1       2.000      near  101     7.855431e-02         0.999950      5.021739e-05      9.214457e-01
36  two_module_task_routed_no_comms       0.001       far  101     8.333333e-01         1.000000      0.000000e+00      1.666667e-01
37  two_module_task_routed_no_comms       0.001      near  101     6.587132e-01         1.000000      1.157162e-07      3.412868e-01
38  two_module_task_routed_no_comms       0.010       far  101     8.333333e-01         1.000000      0.000000e+00      1.666667e-01
39  two_module_task_routed_no_comms       0.010      near  101     6.588075e-01         1.000000      1.111860e-07      3.411925e-01
40  two_module_task_routed_no_comms       0.100       far  101     8.333333e-01         1.000000      0.000000e+00      1.666667e-01
41  two_module_task_routed_no_comms       0.100      near  101     6.588939e-01         1.000000      3.441113e-07      3.411061e-01
42  two_module_task_routed_no_comms       1.000       far  101     8.333333e-01         1.000000      0.000000e+00      1.666667e-01
43  two_module_task_routed_no_comms       1.000      near  101     5.017870e-01         0.999999      5.594415e-07      4.982130e-01
44  two_module_task_routed_no_comms       2.000       far  101     5.451511e-01         1.000000      0.000000e+00      4.548489e-01
45  two_module_task_routed_no_comms       2.000      near  101     9.917092e-04         0.997809      2.190674e-03      9.990083e-01
46      two_module_task_routed_sp05       0.010       far  101     8.333333e-01         1.000000      0.000000e+00      1.666667e-01
47      two_module_task_routed_sp05       0.010      near  101     6.588077e-01         1.000000      1.111786e-07      3.411923e-01
48      two_module_task_routed_sp05       0.100       far  101     8.333333e-01         1.000000      0.000000e+00      1.666667e-01
49      two_module_task_routed_sp05       0.100      near  101     6.589000e-01         1.000000      3.457311e-07      3.411000e-01
50      two_module_task_routed_sp05       1.000       far  101     8.333333e-01         1.000000      0.000000e+00      1.666667e-01
51      two_module_task_routed_sp05       1.000      near  101     5.127934e-01         0.999998      2.383808e-06      4.872066e-01
52       two_module_task_routed_sp1       0.001       far  101     8.333333e-01         1.000000      0.000000e+00      1.666667e-01
53       two_module_task_routed_sp1       0.001      near  101     6.587130e-01         1.000000      1.157268e-07      3.412870e-01
54       two_module_task_routed_sp1       0.010       far  101     8.333333e-01         1.000000      0.000000e+00      1.666667e-01
55       two_module_task_routed_sp1       0.010      near  101     6.588075e-01         1.000000      1.111912e-07      3.411925e-01
56       two_module_task_routed_sp1       0.100       far   56     8.333333e-01         1.000000      0.000000e+00      1.666667e-01
57       two_module_task_routed_sp1       0.100      near   69     6.589009e-01         1.000000      3.476936e-07      3.410991e-01
58       two_module_task_routed_sp1       1.000       far  101     8.333333e-01         1.000000      0.000000e+00      1.666667e-01
59       two_module_task_routed_sp1       1.000      near  101     4.978969e-01         0.999996      3.820238e-06      5.021031e-01
60       two_module_task_routed_sp1       2.000       far  101     6.810725e-01         1.000000      0.000000e+00      3.189275e-01
61       two_module_task_routed_sp1       2.000      near  101     5.048653e-02         0.998505      1.494562e-03      9.495135e-01

## 5. Paper-faithful output table for later notebook merge

This is the participant-level table you can merge back into a figure notebook.

Recommended merge keys:

- `participant`
- `condition`
- plus scenario metadata such as `sim_folder` or (`arch_group`, `init_scale`, `sparsity_label`, `routing`)

In [131]:
if interference_df.empty:
    paper_faithful_interference = pd.DataFrame()
else:
    paper_faithful_interference = interference_df[
        [
            "participant", "condition",
            "arch_group", "routing", "sparsity_label", "init_scale", "sim_folder",
            "A_weight_A2", "kappa_A2", "interference",
        ]
    ].copy()
    paper_faithful_interference = paper_faithful_interference.sort_values(
        ["arch_group", "init_scale", "condition", "participant"]
    )

paper_faithful_interference.head(20)

               participant condition     arch_group routing sparsity_label  init_scale                                         sim_folder  A_weight_A2  kappa_A2  interference
5342   sim_study1_far_sub1       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.842960  0.044213      0.157040
5322  sim_study1_far_sub10       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.854165  0.032577      0.145835
5329  sim_study1_far_sub12       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.455691  1.245715      0.544309
5316  sim_study1_far_sub13       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.131326  0.132679      0.868674
5302  sim_study1_far_sub15       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.470518  0.741167      0.529482
5287  sim_study1_far_sub16       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.071339  0.661771      0.928661
5324  sim_study1_far_sub19       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.341964  1.848712      0.658036
5349  sim_study1_far_sub20       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.142186  0.064794      0.857814
5325  sim_study1_far_sub21       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.848652  0.171076      0.151348
5355  sim_study1_far_sub22       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.345926  2.072103      0.654074
5308  sim_study1_far_sub23       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.329230  2.973189      0.670770
5314  sim_study1_far_sub25       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.639211  2.078693      0.360789
5280  sim_study1_far_sub26       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.140335  0.162000      0.859665
5361  sim_study1_far_sub27       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.147897  1.440625      0.852103
5283  sim_study1_far_sub28       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.090431  0.419190      0.909569
5319  sim_study1_far_sub29       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.102303  0.592592      0.897697
5303  sim_study1_far_sub30       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.167645  0.090977      0.832355
5284  sim_study1_far_sub32       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.102886  0.629159      0.897114
5279  sim_study1_far_sub33       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.873614  0.262609      0.126386
5360  sim_study1_far_sub34       far  single_module  shared  single_module       0.001  single_module_rnn_50_nb2_init0.001_nb2_shared_...     0.256390  1.118022      0.743610

## 6. Optional export

Uncomment the save line if you want one combined CSV for the tested primary grid.

In [132]:
export_path = project_root / "data" / "simulations" / "size25_taskrouted_primary_vonmises_interference_summary.csv"
# paper_faithful_interference.to_csv(export_path, index=False)
export_path

PosixPath('/home/kat/workspace/Structure-Function-Analysis-of-Network-Topologies/a1b2_modular/data/simulations/size25_taskrouted_primary_vonmises_interference_summary.csv')